language: java
jdk:
   - openjdk14
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check
deploy:
   provider: heroku
   api_key: $HEROKU_TOKEN 
   app: "book-demo-store-tdd"
   on:
      branch: "main"
 